### ISSUE TITLE
Thought process revamp

### ISSUE THREAD

**Issue by julia-pearson-15** [julia-pearson/ledger#3]
Hi Anna,

I am at act 5 (collecting people's debts and putting them into my own pocket). For the rest of the actions I have been using the method .split(' ') on the string input and locating the appropriate commands/cash change. This has been only mildly tedious but with part 5 it will take a very long time to get that value off of the appropriate place on my ledger. 

Should I have approached my whole strategy differently? Somehow using objects instead?

**Comment by phlco** [comment]
@julia-pearson can you explain what you mean by "very long time?" Is this miliseconds, years? :)

**Comment by julia-pearson-15** [comment]
sorry not time in running, but time to coding. I would need to search through the array containing each string/number contained in my ledger. i.e. : 

[Julia, owes, me, 100, ducats, jeff, owes, me, 50, ducats, jane, owes, me, 40, ducats]

match the name and then edit the number three indexes away. 

nameOfDebter = array[0]
cashToAdjust = array[3]

Which I think I can do but just wanted to check if I'm thinking about this all wrong. Maybe I'll switch to some kind of debters object. (I guess this is no longer really a question but more just a decision I can make so my code is dryer)
